import React, { useState, useEffect } from 'react';
import { 
  Settings, 
  Database, 
  Moon, 
  Sun, 
  ShieldCheck, 
  Bell, 
  RotateCcw, 
  CheckCircle2, 
  AlertCircle,
  Eye,
  EyeOff,
  Copy,
  Check,
  UploadCloud,
  RefreshCw,
  Globe,
  Key,
  Code2,
  Trash2,
  Server
} from 'lucide-react';
import { useTheme } from '../context/ThemeContext.jsx';
import { 
  isSupabaseConfigured, 
  getStoredSupabaseConfig, 
  saveSupabaseConfig, 
  clearSupabaseConfig, 
  testCustomSupabaseConnection,
  seedSupabaseInitialData 
} from '../supabase/supabaseClient.js';

const SUPABASE_SCHEMA_SQL = `-- ====================================================================
-- OMP GABON - SCRIPT D'INITIALISATION POSTGRESQL (SUPABASE)
-- Exécutez ce script dans : Supabase Dashboard > SQL Editor > New Query > Run
-- ====================================================================

-- 1. Table des Équipements de manutention et d'extraction portuaire
CREATE TABLE IF NOT EXISTS public.equipements (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code TEXT NOT NULL,
  name TEXT NOT NULL,
  category TEXT NOT NULL,
  location TEXT,
  status TEXT DEFAULT 'Opérationnel',
  criticality TEXT DEFAULT 'Moyenne',
  commissionDate TEXT,
  operatingHours NUMERIC DEFAULT 0,
  downtimeHours NUMERIC DEFAULT 0,
  lastMaintenance TEXT,
  nextMaintenance TEXT,
  serialNumber TEXT,
  manufacturer TEXT,
  notes TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. Table du Registre des Pannes et Défaillances
CREATE TABLE IF NOT EXISTS public.pannes (
  id TEXT PRIMARY KEY,
  equipment TEXT NOT NULL,
  equipmentCode TEXT,
  type TEXT NOT NULL,
  date TEXT,
  time TEXT,
  severity TEXT,
  priority TEXT,
  reportedBy TEXT,
  status TEXT DEFAULT 'En cours',
  durationHours NUMERIC DEFAULT 0,
  symptoms TEXT,
  cause TEXT,
  actionRequired TEXT,
  securityNote TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 3. Table des Ordres de Travail (Work Orders)
CREATE TABLE IF NOT EXISTS public.work_orders (
  id TEXT PRIMARY KEY,
  title TEXT NOT NULL,
  equipment TEXT NOT NULL,
  equipmentCode TEXT,
  technician TEXT,
  type TEXT,
  priority TEXT,
  deadline TEXT,
  status TEXT DEFAULT 'À planifier',
  description TEXT,
  estimatedHours NUMERIC DEFAULT 0,
  spentHours NUMERIC DEFAULT 0,
  partsRequired JSONB,
  actionList JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. Table du Magasin Central et Pièces de Rechange
CREATE TABLE IF NOT EXISTS public.pieces (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  ref TEXT NOT NULL,
  name TEXT NOT NULL,
  category TEXT,
  stock INT DEFAULT 0,
  minStock INT DEFAULT 0,
  unit TEXT DEFAULT 'Unités',
  location TEXT,
  compatibleMachines JSONB,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. Table des Techniciens de Maintenance Portuaire
CREATE TABLE IF NOT EXISTS public.techniciens (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  matricule TEXT NOT NULL,
  name TEXT NOT NULL,
  role TEXT,
  specialty TEXT,
  status TEXT DEFAULT 'Disponible',
  activeOrders INT DEFAULT 0,
  completedOrders INT DEFAULT 0,
  rating NUMERIC DEFAULT 4.5,
  phone TEXT,
  shift TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- Activation de Row Level Security (RLS) et politique d'accès pour clé anon
ALTER TABLE public.equipements ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pannes ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.work_orders ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.pieces ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.techniciens ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Acces public equipements" ON public.equipements FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acces public pannes" ON public.pannes FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acces public work_orders" ON public.work_orders FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acces public pieces" ON public.pieces FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Acces public techniciens" ON public.techniciens FOR ALL USING (true) WITH CHECK (true);
`;

export default function ParametresPage({ 
  onResetData, 
  onReloadData,
  equipments = [],
  pannes = [],
  workOrders = [],
  parts = [],
  technicians = [],
  showToast
}) {
  const { isDarkMode, toggleTheme } = useTheme();
  const [saveSuccess, setSaveSuccess] = useState(false);
  const [criticalThreshold, setCriticalThreshold] = useState(90);
  const [emailAlerts, setEmailAlerts] = useState('maintenance-direction@omp.ga');

  // Configuration Supabase
  const currentConfig = getStoredSupabaseConfig();
  const [supabaseUrl, setSupabaseUrl] = useState(currentConfig.url || '');
  const [supabaseKey, setSupabaseKey] = useState(currentConfig.key || '');
  const [showKey, setShowKey] = useState(false);
  const [isConfigured, setIsConfigured] = useState(isSupabaseConfigured());

  // Tests et synchronisations
  const [isTesting, setIsTesting] = useState(false);
  const [testResult, setTestResult] = useState(null);
  const [isSaving, setIsSaving] = useState(false);
  const [isSeeding, setIsSeeding] = useState(false);
  const [seedResult, setSeedResult] = useState(null);

  // Script SQL
  const [showSqlBlock, setShowSqlBlock] = useState(false);
  const [sqlCopied, setSqlCopied] = useState(false);

  const handleGeneralSave = (e) => {
    e.preventDefault();
    setSaveSuccess(true);
    setTimeout(() => setSaveSuccess(false), 3000);
  };

  // Tester la connexion Supabase
  const handleTestConnection = async () => {
    setIsTesting(true);
    setTestResult(null);
    try {
      const res = await testCustomSupabaseConnection(supabaseUrl, supabaseKey);
      setTestResult(res);
    } catch (err) {
      setTestResult({ success: false, message: `Erreur : ${err.message}` });
    } finally {
      setIsTesting(false);
    }
  };

  // Enregistrer la configuration Supabase
  const handleSaveSupabase = async () => {
    if (!supabaseUrl || !supabaseKey) {
      alert('Veuillez remplir l\'URL et la Clé Publique (Anon) avant d\'enregistrer.');
      return;
    }

    setIsSaving(true);
    try {
      const configured = saveSupabaseConfig(supabaseUrl.trim(), supabaseKey.trim());
      setIsConfigured(configured);
      
      // Test de vérification
      const test = await testCustomSupabaseConnection(supabaseUrl.trim(), supabaseKey.trim());
      setTestResult(test);

      if (onReloadData) {
        await onReloadData();
      }

      if (showToast) {
        showToast('Configuration Supabase enregistrée avec succès !');
      }
    } catch (e) {
      console.error(e);
    } finally {
      setIsSaving(false);
    }
  };

  // Déconnecter / Supprimer la configuration Supabase
  const handleDisconnectSupabase = () => {
    if (window.confirm('Voulez-vous déconnecter Supabase et repasser en mode de stockage local (LocalStorage) ?')) {
      clearSupabaseConfig();
      setSupabaseUrl('');
      setSupabaseKey('');
      setIsConfigured(false);
      setTestResult(null);
      setSeedResult(null);
      if (showToast) {
        showToast('Supabase déconnecté. Mode LocalStorage réactivé.');
      }
    }
  };

  // Injecter les données d'essai du port dans Supabase
  const handleSeedData = async () => {
    if (!isConfigured) {
      alert('Veuillez d\'abord enregistrer une configuration Supabase valide.');
      return;
    }

    if (!window.confirm('Voulez-vous injecter les équipements portuaires, pannes réelles, ordres de travail, pièces et techniciens dans votre base Supabase ?')) {
      return;
    }

    setIsSeeding(true);
    setSeedResult(null);

    try {
      const res = await seedSupabaseInitialData({
        equipments,
        pannes,
        workOrders,
        parts,
        technicians
      });
      setSeedResult(res);

      if (res.success && onReloadData) {
        await onReloadData();
      }
    } catch (err) {
      setSeedResult({ success: false, message: `Échec : ${err.message}` });
    } finally {
      setIsSeeding(false);
    }
  };

  // Copier le script SQL
  const handleCopySql = () => {
    navigator.clipboard.writeText(SUPABASE_SCHEMA_SQL);
    setSqlCopied(true);
    setTimeout(() => setSqlCopied(false), 2500);
  };

  return (
    <div className="content" id="parametres-page-content">
      {/* En-tête de la page */}
      <div className="section-heading" style={{ marginBottom: '28px' }}>
        <div>
          <div className="section-label">CONFIGURATION SYSTÈME &amp; PERSISTANCE</div>
          <div className="section-title" style={{ fontSize: '28px', marginTop: '4px' }}>
            Paramètres &amp; Connexion Supabase
          </div>
          <p style={{ fontSize: '14px', color: 'var(--muted)', marginTop: '4px' }}>
            Gérez la connexion à votre base distante Supabase, les seuils critiques AFNOR et l'affichage de la supervision portuaire.
          </p>
        </div>
      </div>

      {saveSuccess && (
        <div style={{
          padding: '14px 20px',
          background: 'rgba(66,189,103,0.15)',
          border: '1px solid var(--green)',
          borderRadius: '8px',
          color: 'var(--green)',
          display: 'flex',
          alignItems: 'center',
          gap: '10px',
          marginBottom: '20px',
          fontWeight: 600
        }}>
          <CheckCircle2 size={18} />
          Paramètres enregistrés avec succès !
        </div>
      )}

      {/* BLOC PRINCIPAL: CONNEXION SUPABASE EN DIRECT (PLEINE LARGEUR) */}
      <div className="industrial-card" style={{ marginBottom: '28px' }} id="supabase-config-card">
        <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'flex-start', flexWrap: 'wrap', gap: '12px', marginBottom: '18px' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '12px' }}>
            <div style={{
              width: '40px',
              height: '40px',
              borderRadius: '10px',
              background: 'rgba(235,94,40,0.12)',
              display: 'flex',
              alignItems: 'center',
              justifyContent: 'center',
              border: '1px solid rgba(235,94,40,0.3)'
            }}>
              <Database size={22} color="var(--orange)" />
            </div>
            <div>
              <div style={{ fontSize: '18px', fontWeight: 700, color: 'var(--text)' }}>
                Connexion Base de Données Supabase
              </div>
              <div style={{ fontSize: '12px', color: 'var(--muted)' }}>
                Synchronisation en temps réel de la flotte, des ordres de travail et du registre des pannes
              </div>
            </div>
          </div>

          <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
            {isConfigured ? (
              <span className="status-badge status-done" style={{ padding: '6px 12px', fontSize: '12px' }}>
                <CheckCircle2 size={14} style={{ marginRight: '6px' }} />
                Supabase Connecté &amp; Actif
              </span>
            ) : (
              <span className="status-badge status-info" style={{ padding: '6px 12px', fontSize: '12px' }}>
                <Server size={14} style={{ marginRight: '6px' }} />
                Mode Local Actif (LocalStorage Fallback)
              </span>
            )}
          </div>
        </div>

        <p style={{ fontSize: '13px', color: 'var(--muted)', marginBottom: '20px', lineHeight: '1.6' }}>
          Renseignez votre <strong>URL de Projet</strong> et votre <strong>Clé Publique Anon</strong> ci-dessous pour connecter l'application à votre instance Supabase. 
          En l'absence de clés ou en cas de perte de réseau, l'application fonctionne sans interruption grâce au cache local persistant.
        </p>

        {/* Formulaire Supabase */}
        <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fit, minmax(320px, 1fr))', gap: '18px', marginBottom: '20px' }}>
          {/* Champ URL */}
          <div className="form-group">
            <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Globe size={14} color="var(--orange)" />
              <span>URL du Projet Supabase</span>
            </label>
            <input 
              type="url"
              className="form-control"
              placeholder="https://votre-projet.supabase.co"
              value={supabaseUrl}
              onChange={(e) => setSupabaseUrl(e.target.value)}
              id="input-supabase-url"
              style={{ fontFamily: 'monospace', fontSize: '13px' }}
            />
            <span style={{ fontSize: '11px', color: 'var(--muted)', marginTop: '4px', display: 'block' }}>
              Trouvable dans : <em>Supabase Dashboard &gt; Project Settings &gt; API &gt; Project URL</em>
            </span>
          </div>

          {/* Champ Clé Anon */}
          <div className="form-group">
            <label className="form-label" style={{ display: 'flex', alignItems: 'center', gap: '6px' }}>
              <Key size={14} color="var(--orange)" />
              <span>Clé API Publique (Anon Key)</span>
            </label>
            <div style={{ position: 'relative' }}>
              <input 
                type={showKey ? 'text' : 'password'}
                className="form-control"
                placeholder="eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9..."
                value={supabaseKey}
                onChange={(e) => setSupabaseKey(e.target.value)}
                id="input-supabase-key"
                style={{ fontFamily: 'monospace', fontSize: '13px', paddingRight: '40px' }}
              />
              <button
                type="button"
                onClick={() => setShowKey(!showKey)}
                style={{
                  position: 'absolute',
                  right: '10px',
                  top: '50%',
                  transform: 'translateY(-50%)',
                  background: 'none',
                  border: 'none',
                  color: 'var(--muted)',
                  cursor: 'pointer',
                  padding: '4px'
                }}
                title={showKey ? 'Masquer la clé' : 'Afficher la clé'}
              >
                {showKey ? <EyeOff size={16} /> : <Eye size={16} />}
              </button>
            </div>
            <span style={{ fontSize: '11px', color: 'var(--muted)', marginTop: '4px', display: 'block' }}>
              Trouvable dans : <em>Supabase Dashboard &gt; Project Settings &gt; API &gt; Project API keys (anon / public)</em>
            </span>
          </div>
        </div>

        {/* Message de résultat du test de connexion */}
        {testResult && (
          <div style={{
            padding: '12px 16px',
            borderRadius: '8px',
            marginBottom: '20px',
            display: 'flex',
            alignItems: 'center',
            gap: '10px',
            fontSize: '13px',
            background: testResult.success ? 'rgba(66,189,103,0.12)' : 'rgba(239,71,111,0.12)',
            border: `1px solid ${testResult.success ? 'var(--green)' : 'var(--red)'}`,
            color: testResult.success ? 'var(--green)' : 'var(--red)'
          }}>
            {testResult.success ? <CheckCircle2 size={18} /> : <AlertCircle size={18} />}
            <div style={{ flex: 1 }}>{testResult.message}</div>
          </div>
        )}

        {/* Message de résultat de l'injection des données */}
        {seedResult && (
          <div style={{
            padding: '12px 16px',
            borderRadius: '8px',
            marginBottom: '20px',
            display: 'flex',
            alignItems: 'center',
            gap: '10px',
            fontSize: '13px',
            background: seedResult.success ? 'rgba(66,189,103,0.12)' : 'rgba(239,71,111,0.12)',
            border: `1px solid ${seedResult.success ? 'var(--green)' : 'var(--red)'}`,
            color: seedResult.success ? 'var(--green)' : 'var(--red)'
          }}>
            {seedResult.success ? <CheckCircle2 size={18} /> : <AlertCircle size={18} />}
            <div style={{ flex: 1 }}>{seedResult.message}</div>
          </div>
        )}

        {/* Barre des boutons d'actions */}
        <div style={{ display: 'flex', flexWrap: 'wrap', gap: '12px', alignItems: 'center' }}>
          <button
            type="button"
            className="btn-primary"
            onClick={handleSaveSupabase}
            disabled={isSaving}
            id="btn-save-supabase"
            style={{ display: 'flex', alignItems: 'center', gap: '8px' }}
          >
            <CheckCircle2 size={16} />
            {isSaving ? 'Enregistrement...' : 'Enregistrer & Connecter'}
          </button>

          <button
            type="button"
            className="btn-secondary"
            onClick={handleTestConnection}
            disabled={isTesting || !supabaseUrl || !supabaseKey}
            id="btn-test-supabase"
            style={{ display: 'flex', alignItems: 'center', gap: '8px' }}
          >
            <RefreshCw size={15} className={isTesting ? 'animate-spin' : ''} />
            {isTesting ? 'Vérification...' : 'Tester la connexion'}
          </button>

          {isConfigured && (
            <>
              <button
                type="button"
                className="btn-secondary"
                onClick={handleSeedData}
                disabled={isSeeding}
                id="btn-seed-supabase"
                style={{ display: 'flex', alignItems: 'center', gap: '8px', borderColor: 'var(--orange)', color: 'var(--orange)' }}
                title="Injecter les engins, pannes et ordres de travail portuaires si les tables Supabase sont vides"
              >
                <UploadCloud size={16} />
                {isSeeding ? 'Injection des données...' : 'Injecter les données d\'essai dans Supabase'}
              </button>

              <button
                type="button"
                className="btn-secondary"
                onClick={handleDisconnectSupabase}
                id="btn-disconnect-supabase"
                style={{ display: 'flex', alignItems: 'center', gap: '8px', color: 'var(--red)', borderColor: 'rgba(239,71,111,0.4)' }}
              >
                <Trash2 size={15} />
                Déconnecter Supabase
              </button>
            </>
          )}

          <button
            type="button"
            className="btn-secondary"
            onClick={() => setShowSqlBlock(!showSqlBlock)}
            id="btn-toggle-sql"
            style={{ display: 'flex', alignItems: 'center', gap: '8px', marginLeft: 'auto' }}
          >
            <Code2 size={16} />
            {showSqlBlock ? 'Masquer le script SQL' : 'Voir le script SQL des 5 tables'}
          </button>
        </div>

        {/* Accordéon Script SQL */}
        {showSqlBlock && (
          <div style={{
            marginTop: '20px',
            padding: '16px',
            background: 'var(--card-bg)',
            border: '1px solid var(--border)',
            borderRadius: '8px'
          }}>
            <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '12px' }}>
              <div>
                <div style={{ fontSize: '14px', fontWeight: 600, color: 'var(--text)' }}>
                  Script SQL à exécuter dans Supabase (Tables &amp; Droits RLS)
                </div>
                <div style={{ fontSize: '12px', color: 'var(--muted)' }}>
                  Copiez ce code et collez-le dans le <strong>SQL Editor</strong> de Supabase pour créer les tables <code>equipements</code>, <code>pannes</code>, <code>work_orders</code>, <code>pieces</code>, <code>techniciens</code>.
                </div>
              </div>

              <button
                type="button"
                className="btn-primary"
                onClick={handleCopySql}
                style={{ display: 'flex', alignItems: 'center', gap: '6px', fontSize: '12px', padding: '6px 14px' }}
              >
                {sqlCopied ? <Check size={14} /> : <Copy size={14} />}
                {sqlCopied ? 'Script copié !' : 'Copier le script SQL'}
              </button>
            </div>

            <pre style={{
              margin: 0,
              padding: '14px',
              background: 'rgba(0,0,0,0.25)',
              borderRadius: '6px',
              fontSize: '12px',
              fontFamily: 'Consolas, Monaco, monospace',
              color: 'var(--text)',
              maxHeight: '260px',
              overflowY: 'auto',
              whiteSpace: 'pre-wrap',
              border: '1px solid var(--border)'
            }}>
              {SUPABASE_SCHEMA_SQL}
            </pre>
          </div>
        )}
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '24px' }}>
        {/* CARTE 1: THÈME VISUEL & APPARENCE (Bleu Nuit) */}
        <div className="industrial-card">
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
            <Moon size={20} color="var(--orange)" />
            <div style={{ fontSize: '16px', fontWeight: 700, color: 'var(--text)' }}>
              Apparence &amp; Thème Visuel
            </div>
          </div>

          <p style={{ fontSize: '13px', color: 'var(--muted)', marginBottom: '16px', lineHeight: '1.5' }}>
            Basculez entre le thème standard Haute Luminosité et le mode <strong>Sombre Bleu Nuit</strong> (#051326 / #0b1e38) adapté aux salles de contrôle portuaires 24/7.
          </p>

          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', padding: '14px', background: 'var(--hover-bg)', borderRadius: '8px' }}>
            <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
              {isDarkMode ? <Moon size={18} color="var(--orange)" /> : <Sun size={18} color="var(--orange)" />}
              <div>
                <div style={{ fontSize: '14px', fontWeight: 600, color: 'var(--text)' }}>
                  {isDarkMode ? 'Mode Sombre (Bleu Nuit Actif)' : 'Mode Clair (Standard)'}
                </div>
                <div style={{ fontSize: '12px', color: 'var(--muted)' }}>
                  {isDarkMode ? 'Palette #051326 contrastée pour la nuit' : 'Palette blanche industrielle standard'}
                </div>
              </div>
            </div>

            <button
              type="button"
              className="btn-primary"
              onClick={toggleTheme}
              id="btn-toggle-theme-page"
            >
              {isDarkMode ? 'Basculer en Blanc' : 'Basculer en Bleu Nuit'}
            </button>
          </div>
        </div>

        {/* CARTE 3: SEUILS D'ALERTE AFNOR */}
        <div className="industrial-card">
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
            <Bell size={20} color="var(--orange)" />
            <div style={{ fontSize: '16px', fontWeight: 700, color: 'var(--text)' }}>
              Alertes &amp; Tolérances Critiques
            </div>
          </div>

          <form onSubmit={handleGeneralSave}>
            <div className="form-group">
              <label className="form-label">Seuil Minimal de Disponibilité (Do %)</label>
              <input 
                type="number"
                className="form-control"
                value={criticalThreshold}
                onChange={(e) => setCriticalThreshold(Number(e.target.value))}
              />
              <span style={{ fontSize: '11px', color: 'var(--muted)', marginTop: '2px' }}>
                Déclenche une alerte rouge si le parc descend sous ce pourcentage.
              </span>
            </div>

            <div className="form-group" style={{ marginTop: '12px' }}>
              <label className="form-label">Email Notification Astreinte 24/7</label>
              <input 
                type="email"
                className="form-control"
                value={emailAlerts}
                onChange={(e) => setEmailAlerts(e.target.value)}
              />
            </div>

            <button type="submit" className="btn-primary" style={{ marginTop: '16px' }}>
              Enregistrer les Seuils
            </button>
          </form>
        </div>

        {/* CARTE 4: MAINTENANCE DE LA BASE DE DONNÉES */}
        <div className="industrial-card" style={{ gridColumn: '1 / -1' }}>
          <div style={{ display: 'flex', alignItems: 'center', gap: '10px', marginBottom: '16px' }}>
            <RotateCcw size={20} color="var(--red)" />
            <div style={{ fontSize: '16px', fontWeight: 700, color: 'var(--text)' }}>
              Réinitialisation des Données d'Usine
            </div>
          </div>

          <p style={{ fontSize: '13px', color: 'var(--muted)', marginBottom: '16px', lineHeight: '1.5' }}>
            Restaurez les données d'échantillon d'origine du Port d'Owendo (Pelle mécanique, Chargeuse, Dumper, Bulldozer, Tracteur, Camion, Tractopelle, pannes et ordres de travail).
          </p>

          <button
            type="button"
            className="btn-secondary"
            style={{ color: 'var(--red)', borderColor: 'var(--red)' }}
            onClick={() => {
              if (window.confirm('Voulez-vous réinitialiser toutes les données locales avec le jeu d\'essai initial du port ?')) {
                onResetData();
              }
            }}
          >
            <RotateCcw size={14} /> Réinitialiser les données d'usine
          </button>
        </div>
      </div>
    </div>
  );
}
